name: rubfiber.github.io deployment

on:
  workflow_dispatch:
  push:
    branches:
      -main

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      # check repo
      - name: Checkout code
        uses: actions/checkout@v3

    # Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
      # Install dependencies
      - name: Install Dependencies
        run: npm install
      # Build project
      - name: Build Project
        run: npm run build
      # Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-page@v3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: dist